### ISSUE TITLE
Get 400 Error, but only when deployed on firebase functions. Works in localhost - Same code

### ISSUE THREAD

**Issue by AndreJLouw** [google-gemini/generative-ai-js#239]
### Description of the bug:

GoogleGenerativeAIFetchError: [GoogleGenerativeAI Error]: Error fetching from https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:embedContent: [400 Bad Request] User location is not supported for the API use.
    at handleResponseNotOk (/workspace/node_modules/@google/generative-ai/dist/index.js:403:11)

### Actual vs expected behavior:

Completion of request

### Any other information you'd like to share?

This worked before, and suddenly just stopped. The API key is on the paid account.

Firebase location: us-central1

**Comment by gitton** [comment]
Getting same error

**Comment by devberkay** [comment]
Same setup and same problem.

**Comment by ruuuruiya** [comment]
Same error here, us-central1

**Comment by BernardasJuzumas** [comment]
same. Firebase function, deployed in us-central1. Tried redeploying to eu-west - same. It worked well several hrs ago. Any change in api?

**Comment by romainwurtz** [comment]
Same issue on AppEngine with `us-west2`

**Comment by ak--47** [comment]
_same_ `us-central1`

```
GoogleGenerativeAIFetchError: [GoogleGenerativeAI Error]: Error fetching from https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent: [400 Bad Request] User location is not supported for the API use.
    at handleResponseNotOk (file:///workspace/node_modules/@google/generative-ai/dist/index.mjs:401:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async makeRequest (file:///workspace/node_modules/@google/generative-ai/dist/index.mjs:374:9)
    at async generateContent (file:///workspace/node_modules/@google/generative-ai/dist/index.mjs:813:22)
```

**Comment by GanderwaD** [comment]
same problem

**Comment by robertedjones** [comment]
Same here, @hsubox76 any insight on what the problem is?

**Comment by egisz** [comment]
Same here, **us-central1**, functions v2. Switched function to **us-west1** - works.
But this is not solution if functions are called from app :(

**Comment by BernardasJuzumas** [comment]
Found another discussion here: https://discuss.ai.google.dev/t/generate-object-error-user-location-is-not-supported-for-the-api-use/37440/21
Could possibly be related to gemini api geoblocking ips of firebase/gcp cloud function calls that originate from "us-central1".
The only real solution here is to deploy to several regions simultaneously and implement a failover if one region fails.
