### ISSUE TITLE
functionResponse: Unable to submit request because it must have a text parameter.

### ISSUE THREAD

**Issue by LaKing** [google-gemini/generative-ai-js#316]
### Description of the bug:

According to the documentation the results to the tool function calls should be submitted with the functionResponse, where response is a json object.

```javascript
                              const submit = await chat.sendMessage([
                                    {
                                        functionResponse: {
                                            name,
                                            response: { content: "output" },
                                        },
                                    },
                                ]);
```

Here name is a valid string, and "output" is obviously a valid string. Therefore, I assume, this is a bug.
I have extensively looked up all documentation, examples, and this should work, .... but I'm unable to send back any results to the model.
I have tried this within the response stream, and also by collecting all results and sending them once the stream completed.

```
Error: [GoogleGenerativeAI Error]: 
Error fetching from https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash-exp:streamGenerateContent?alt=sse: 
[400 Bad Request] Unable to submit request because it must have a text parameter. 
Add a text parameter and try again. 
Learn more: https://cloud.google.com/vertex-ai/generative-ai/docs/model-reference/gemini
```

**Comment by randofan** [comment]
I'm encountering the same issue with function calling. Running this as part of an express.js server, it works perfectly on localhost using the Firebase emulator, but this issue arises when deployed with Firebase functions. Once I see this error message, any subsequent messages (including non-function calls) result in the same error.

**Comment by mostafa-gado** [comment]
I am having the same issue! Any fix came up?

**Comment by ziyanali30** [comment]
having the same issue still no fix? @google-admin

**Comment by hkt74** [comment]
Hi @LaKing 

I think this is working as intended, `functionResponse` cannot be used independently.

It needs to understand the text prompt and function call arguments, usually it works in following sequence, use chat as example.

1. client side: define a function declaration and include it in model's tools
2. client side: send a text prompt to model
3. model side: model returns function call argument
4. client side: call the function locally with function call argument
5. client side:  send function response to model
6. model side: return the final result.

see this [tutorial](https://ai.google.dev/gemini-api/docs/function-calling/tutorial?lang=node) for more details, thanks

**Comment by hkt74** [comment]
Hi @mostafa-gado 

If you follow the same steps and using chat to send messages in sequence, I guess it might because the text content or the function call was rejected by the model.

I suggest to print the chat history to debug the received contents from the model.

I tried the [function calling sample](https://github.com/google-gemini/generative-ai-js/blob/main/samples/function_calling.js) , it works for me, see the history logs

```
role: user, part: {"text":"Dim the lights so the room feels cozy and warm."}
role: model, part: {"functionCall":{"name":"controlLight","args":{"brightness":30,"colorTemperature":"warm"}}}
role: function, part: {"functionResponse":{"name":"controlLight","response":{"brightness":30,"colorTemperature":"warm"}}}
role: model, part: {"text":"OK. I've dimmed the lights to 30% brightness and set the color temperature to warm.  Let me know if you'd like to adjust them further.\n"}
```

I use this log

```
const contents = await chat.getHistory();
for (const content of contents) {
  console.log('role: %s, part: %s', content.role, JSON.stringify(content.parts[0]));
}
```

**Comment by nelsonzheng** [comment]
I had the same issue and resolved it by passing in an empty text string
```
"contents": [
  {
    "role": 'user',
    "parts": [
      {
        "text": '',
        "fileData": {
          "mimeType": $mimeType,
          "fileUri": $fileUri
        }
      }
    ]
  }
]
```

**Comment by LaKing** [comment]
@hkt74 please help me understand where the text parameter should be located.

```javascript
import { GoogleGenerativeAI } from "@google/generative-ai";
async function functionCalling() {
    const controlLightFunctionDeclaration = {
        name: "setLightValues",
        parameters: {
            type: "OBJECT",
            description: "Set the brightness and color temperature of a room light.",
            properties: {
                brightness: {
                    type: "NUMBER",
                    description: "Light level from 0 to 100. Zero is off and 100 is full brightness.",
                },
                colorTemperature: {
                    type: "STRING",
                    description: "Color temperature of the light fixture which can be `daylight`, `cool` or `warm`.",
                },
            },
            required: ["brightness", "colorTemperature"],
        },
    };

    async function setLightValues({ brightness, colorTemperature } = {}) {
        return {
            brightness,
            colorTemperature,
        };
    }

    const functions = {
        setLightValues,
    };

    const genAI = new GoogleGenerativeAI(process.env.API_KEY);

    // 1. client side: define a function declaration and include it in model's tools
    const model = genAI.getGenerativeModel({
        model: "gemini-2.0-flash-exp",
        tools: { functionDeclarations: [controlLightFunctionDeclaration] },
    });

    const chat = model.startChat();

    // 2. client side: send a text prompt to model
    const prompt = "Dim the lights so the room feels cozy and warm.";
    let result = await chat.sendMessageStream(prompt);

    for await (const e of result.stream) {
        // 3. model side: model returns function call argument
        const chunk = e.text();
        const calls = e.functionCalls();
        console.log("chunk:", chunk, "calls:", calls);

        if (calls) {
            for (const { name, args } of calls)
                if (functions[name]) {
                    // 4. client side: call the function locally with function call argument

                    console.log("Calling " + name);
                    const output = await functions[name](args);

                    console.log("Send function response to model", output);
                    // 5. client side: send function response to model
                    const modelResponse = await chat.sendMessage([
                        {
                            functionResponse: {
                                name,
                                response: output,
                            },
                        },
                    ]);
                    console.log("modelResponse", modelResponse.response.text());
                }
        }
    }
}

functionCalling();

/*
Error: Command failed: /bin/node /srv/hangmaffia-project/@ai-modules/gemini/gemini-test.mjs
file:///srv/boilerplate4/@ai-modules/gemini/node_modules/@google/generative-ai/dist/index.mjs:412
    throw new GoogleGenerativeAIFetchError(`Error fetching from ${url.toString()}: [${response.status} ${response.statusText}] ${message}`, response.status, response.statusText, errorDetails);
          ^

GoogleGenerativeAIFetchError: [GoogleGenerativeAI Error]: Error fetching from https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash-exp:generateContent: 
	[400 Bad Request] Unable to submit request because it must have a text parameter. Add a text parameter and try again. Learn more: https://cloud.google.com/vertex-ai/generative-ai/docs/model-reference/gemini
    at handleResponseNotOk (file:///srv/boilerplate4/@ai-modules/gemini/node_modules/@google/generative-ai/dist/index.mjs:412:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async makeRequest (file:///srv/boilerplate4/@ai-modules/gemini/node_modules/@google/generative-ai/dist/index.mjs:385:9)
    at async generateContent (file:///srv/boilerplate4/@ai-modules/gemini/node_modules/@google/generative-ai/dist/index.mjs:830:22)
    at async ChatSession.sendMessage (file:///srv/boilerplate4/@ai-modules/gemini/node_modules/@google/generative-ai/dist/index.mjs:1144:9)
    at async run (file:///srv/boilerplate4/@ai-modules/gemini/gemini-test.mjs:102:39) {
  status: 400,
  statusText: 'Bad Request',
  errorDetails: undefined
}
*/
```

Thank you.

**Comment by hkt74** [comment]
Hi @LaKing 

thanks for sharing the code snippet, I could reproduce the error, it was caused by a bug with the streaming response aggregation. The issue was preventing the chat history from being properly appended with the chunks response.

the sample code uses sendMessage thats why it couldn't reproduce the error. 

Could you try updating to the latest version, v0.22.0, and see if that resolves the problem for you?

```
npm install @google/generative-ai
```

after installing 0.22, the error should disappear, I verified it locally.

**Comment by LaKing** [comment]
Thank you Kaituo, now it works! ...
